### ISSUE TITLE
The templates can not be properly used

### ISSUE THREAD

**Issue by JayLiu7319** [thaider/SemanticOrganization-Docker#2]
Hi, I found this repo because of your Semanti Organization project. This work is excellent and impressive! But when I use the organization extension, some fatal error occured. 
I'm using tweeki skin and it works well in my website. I followed the installion guide and when I use the templates from the organization extension, I can't get the proper result as your site https://semorg.kollabor.at/wiki/Groups.
Maybe I missing some important components? Such as some custom file?

![image](https://user-images.githubusercontent.com/16852190/147328773-fd1a519c-8da9-4d22-b7e7-e1581c8fcb6f.png)

**Comment by thaider** [comment]
From what I can see you haven't installed the ParserFunction extension. Please have a look at the [full installation instructions](https://semorg.kollabor.at/wiki/Full_Installation_Instructions) of the documentation. Depending on how you installed MediaWiki it might be enough to put the following line in ```LocalSettings.php```:

```
wfLoadExtension('ParserFunctions');
```
